{
 "title": "CloudPulse Application Monitor",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Source", "query": "prometheus" },
   { "name": "loki_ds", "label": "Loki Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "App Server Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up{instance='10.0.0.10:80'}" }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])"
    }
   ]
  },
  {
   "title": "Live Application Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"cloudpulse\"}"
    }
   ]
  }
 ]
}